[package]
name = "ghidracraft"
version = "0.1.0"
authors = ["Anciety <anciety@starcross.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
clap = { git = "https://github.com/clap-rs/clap/"}
easy-repl = { git = "https://github.com/Escapingbug/easy-repl.git", branch = "different_types" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.4"
parse_int = "0.5"
num-traits = "0.2"
pcodecraft = { git = "https://github.com/StarCrossPortal/pcodecraft.git", features = ["ghidra"] }

[build-dependencies]
cxx-build = "1.0"
filetime = "0.2"

[[bin]]
name = "decompile"
path = "src/main.rs"